version: "3.8"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/reto-3-wordpress.site/fullchain.pem:/etc/letsencrypt/live/reto-3-wordpress.site/fullchain.pem
      - /etc/letsencrypt/live/reto-3-wordpress.site/privkey.pem:/etc/letsencrypt/live/reto-3-wordpress.site/privkey.pem
