version: "3.8"

services:
  wordpress:
    image: wordpress:latest
    ports:
      - "80:80"
    env_file:
      - ./wordpress/.env
    environment:
      WORDPRESS_DB_HOST: 10.128.0.14
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wp_data:/var/www/html
